apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment_name}
spec:
  replicas: 3 # 副本數 擴展數量
  selector:
    matchLabels:
      app: fuse-app # 選擇Pod時的標籤
  template:
    metadata:
      labels:
        app: fuse-app # 選擇Pod時的標籤
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Balanced
        supported-cpu-platform.cloud.google.com/Intel_Cascade_Lake: "true"
      terminationGracePeriodSeconds: 300
      serviceAccountName: gke-access-gcs
      containers:
        - name: ${container_name}
          image: ${image_name}
          resources:
              requests:
                cpu: "2000m"
                memory: "2Gi"
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: ${Key_name}
            - name: database
              value: ${env_database}
            - name: table
              value: ${env_table}
            - name: dataset
              value: ${env_dataset}