apiVersion: v1
kind: Pod
metadata:
  name: embulk
spec:
  terminationGracePeriodSeconds: 300
  containers:
    - name: embulk-container
      image: asia.gcr.io/datapool-1806/k8s-embulk:1.1.1
      env:
        - name: DIGDAG_USER
          valueFrom:
            secretKeyRef:
              name: digdag-secret
              key: DIGDAG_USER
        - name: DIGDAG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: digdag-secret
              key: DIGDAG_PASSWORD
        - name: LIT_PASSWORD_PRD
          valueFrom:
            secretKeyRef:
              name: digdag-secret
              key: LIT_PASSWORD_PRD
        - name: LIT_PASSWORD_DEV
          valueFrom:
            secretKeyRef:
              name: digdag-secret
              key: LIT_PASSWORD_DEV
  restartPolicy: Always
