apiVersion: v1
kind: Pod
metadata:
  name: embulk
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  serviceAccountName: k8s-digdag-server
  containers:
    - name: ${container_name}
      image: ${image_name}
      volumeMounts:
      - name: gcs-fuse-csi-ephemeral
        mountPath: /app/migo_dbt/edr_target
        readOnly: false
  volumes:
  - name: gcs-fuse-csi-ephemeral
    csi:
      driver: gcsfuse.csi.storage.gke.io
      readOnly: false
      volumeAttributes:
        bucketName: ${bucket_name}
        mountOptions: "implicit-dirs"
  restartPolicy: Always
